# Site settings
title: Self Hack
email: selfhackoftheday@gmail.com
description: Personal website to display self hack tips
#baseurl: "/highlights-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
notion_url: 
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

timezone: EST