name: nightly_build

on:
  schedule:
    - cron: '0 4 * * *'  #scheduled for midnight (EST)
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild
        run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/SelfHack/SelfHack.github.io/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: $
