name: test_env_var

on: [workflow_dispatch]
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild
        run: |
          curl --fail --request POST \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer $USER_TOKEN" \
            --url  https://api.github.com/repos/SelfHack/SelfHack.github.io/pages/builds
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
