name: test_env_var

on: [workflow_dispatch]
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $USER_TOKEN" \
            https://api.github.com/repos/SelfHack/SelfHack.github.io/pages/builds
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
