name: nightly_build

on:
  schedule:
    - cron: '0 5 * * *'  #scheduled for midnight (EST)
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Token: $USER_TOKEN"
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
